---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: opscode-ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  - name: opscode_centos-6.5
    driver_config:
      box: opscode_centos-6.5
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
suites:
  - name: default
    run_list:
      - recipe[logstash_forwarder::default]
      - recipe[minitest-handler]
    attributes:

settings:
  parallel: true
